CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255),
  email VARCHAR(255) NOT NULL,
  CONSTRAINT pk_users PRIMARY KEY (id),
  CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(50) NOT NULL,
  CONSTRAINT pk_categories PRIMARY KEY (id),
  CONSTRAINT uq_category_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  lat FLOAT(6) NOT NULL,
  lon FLOAT(6) NOT NULL,
  CONSTRAINT pk_locations PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  annotation VARCHAR,
  category_id BIGINT REFERENCES categories(id),
  confirmedRequests INTEGER,
  createdOn TIMESTAMP NOT NULL,
  description VARCHAR,
  eventDate TIMESTAMP NOT NULL,
  initiator_id BIGINT REFERENCES users(id) NOT NULL,
  location_id BIGINT REFERENCES locations(id),
  paid BOOLEAN,
  participantLimit INTEGER,
  publishedOn TIMESTAMP NOT NULL,
  requestModeration BOOLEAN,
  state VARCHAR(255),
  title VARCHAR(120),
  views BIGINT,
  CONSTRAINT pk_events PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS compilations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  title VARCHAR(50) NOT NULL,
  pinned BOOLEAN,
  CONSTRAINT pk_compilations PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS compilation_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  compilation_id BIGINT REFERENCES compilations(id),
  event_id BIGINT REFERENCES events(id),
  CONSTRAINT pk_compilation_events PRIMARY KEY (id)
);